all:
	$(MAKE) -C ..

gen:
	$(MAKE) -C .. $@


#.PHONY: clean gen cleanall
#
#all:
#	@nim make.nims
#
#gen:
#	@nim make.nims $@
#
#clean:
#	@nim make.nims $@
#
#cleanall:
#	@nim make.nims $@
#
#cleanlib:
#	@nim make.nims $@
#
##MAKEFLAGS += --no-print-directory
