.PHONY: clean gen cleanall

all:
	@nim make.nims

gen:
	@nim make.nims $@

clean: cleanall
	@nim make.nims $@

cleanall:
	@nim make.nims $@

cleanlib:
	@nim make.nims $@

#MAKEFLAGS += --no-print-directory
