name: Linux OS(Debian / Ubuntu) 0.16.0-dev compilation-

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux_dev:

    runs-on: ubuntu-22.04


    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: mlugg/setup-zig@v2
      with:
        version: master
    - name: make
      run: |
        sudo apt install libopengl-dev
        sudo apt install libglfw3 libglfw3-dev
        make zig V=1
